(defpackage :bianet-mesh
  (:use 
   :bianet-neuron 
   :cl 
   :cl-ppcre
   :dc-dlist 
   :dc-eclectic 
   :sb-concurrency 
   :sb-thread)
  (:local-nicknames (:t :transducers))
  (:export
   apply-error
   apply-inputs
   clear-directory
   create-sample-set
   csv-label-sample-size
   csv-sample-labels
   data-set-directory-to-csv
   data-set-file-counts
   data-set-files
   data-set-path
   disable
   ensure-directory-string
   enable
   example-label-file
   excite
   feed-forward
   get-labels
   infer-label-directory-files
   isolate
   label-count
   label-index
   label-outputs
   label-sample-size
   label-vector
   list-incoming
   list-outgoing
   list-outputs
   make-simple-network
   normalize-sample-set
   output-labels
   output-layer-error
   outputs-label
   path-tail
   png-to-inputs
   read-png
   restore-train-files
   separate-test-files
   split-csv-line
   stringify
   subdirectory-names
   train-frame
   wait-for-backprop
   wait-for-backprop-p
   wait-for-output
   wait-for-output-p
   with-neurons
   with-simple-network
   ))
